version: "3.8"

services:
  stocks-db:
    image: "postgres:16"
    container_name: "stocks"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always

  issuer_service:
    build:
      context: Domashna4/IssuerService

    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://diellza:diellza123@stocks-db:5432/stocks
    depends_on:
      - stocks-db
    networks:
      - mynetwork
    restart: always

  data_fetching_service:
    build:
      context: Domashna4/DataFetchingService
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://diellza:diellza123@stocks-db:5432/stocks
    depends_on:
      - stocks-db
    networks:
      - mynetwork
    restart: always

  frontend:
    build:
      context: Domashna2/frontend
    ports:
      - "3000:80"
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge