version: "3.8"
services:
  stocks-db:
    image: "postgres:16"
    container_name: "stocks"
    environment:
      - POSTGRES_USER=diellza
      - POSTGRES_PASSWORD=diellza123
      - POSTGRES_DB=stocks
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: Domashna1/Dockerfile
    container_name: "backend-container"
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=DIANSProject.settings
      - DATABASE_URL=postgresql://diellza:diellza123@stocks:5432/stocks
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - stocks-db

  frontend:
    build:
      context: ./Domashna2/frontend
      dockerfile: Dockerfile
    container_name: "frontend-container"
    volumes:
      - ./path-to-frontend:/app
    ports:
      - "3000:3000"
