# Generated by Django 5.1.2 on 2024-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('last_transaction_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('min_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('percentage_change', models.DecimalField(decimal_places=3, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('best_traded', models.DecimalField(decimal_places=3, max_digits=20)),
                ('total_traded', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
