apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dians-project
  labels:
    app: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hydrangea19/dians_project:frontend-latest
        ports:
        - containerPort: 80