# Generated by Django 5.0.6 on 2024-10-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('last_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('maximum', models.DecimalField(decimal_places=3, max_digits=15)),
                ('minimum', models.DecimalField(decimal_places=3, max_digits=15)),
                ('average_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('percentage_change', models.DecimalField(decimal_places=3, max_digits=15)),
                ('volume', models.IntegerField()),
                ('turnover_best', models.IntegerField()),
                ('total_turnover', models.IntegerField()),
            ],
        ),
    ]
