name: CI Pipeline - Lint Only and Build/Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python for Issuer Service
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Issuer Service Dependencies
        working-directory: Domashna4/IssuerService
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Lint Issuer Service with Flake8
        working-directory: Domashna4/IssuerService
        run: flake8 .

      - name: Set up Python for Data Fetching Service
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Data Fetching Service Dependencies
        working-directory: Domashna4/DataFetchingService
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Lint Data Fetching Service with Flake8
        working-directory: Domashna4/DataFetchingService
        run: flake8 .

      - name: Lint Issuer Service Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Domashna4/IssuerService/Dockerfile

      - name: Lint Data Fetching Service Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Domashna4/DataFetchingService/Dockerfile

      - name: Lint Frontend Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Domashna2/frontend/Dockerfile

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: hydrangea19/dians_project
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Issuer Service image
        run: |
          docker build -t $DOCKERHUB_REPO:issuer_service-latest -f Domashna4/IssuerService/Dockerfile Domashna4/IssuerService
          docker push $DOCKERHUB_REPO:issuer_service-latest

      - name: Build and push Data Fetching Service image
        run: |
          docker build -t $DOCKERHUB_REPO:data_fetching_service-latest -f Domashna4/DataFetchingService/Dockerfile Domashna4/DataFetchingService
          docker push $DOCKERHUB_REPO:data_fetching_service-latest

      - name: Build and push Frontend image
        run: |
          docker build -t $DOCKERHUB_REPO:frontend-latest -f Domashna2/frontend/Dockerfile Domashna2/frontend
          docker push $DOCKERHUB_REPO:frontend-latest
