name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: hydrangea19/dians_project 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Issuer Service image
        run: |
          docker build -t $DOCKERHUB_REPO/issuer_service:latest -f Domashna4/IssuerService/Dockerfile Domashna4/IssuerService
          docker push $DOCKERHUB_REPO/issuer_service:latest

      - name: Build and push Data Fetching Service image
        run: |
          docker build -t $DOCKERHUB_REPO/data_fetching_service:latest -f Domashna4/DataFetchingService/Dockerfile Domashna4/DataFetchingService
          docker push $DOCKERHUB_REPO/data_fetching_service:latest

      - name: Build and push Frontend image
        run: |
          docker build -t $DOCKERHUB_REPO/frontend:latest -f Domashna2/frontend/Dockerfile Domashna2/frontend
          docker push $DOCKERHUB_REPO/frontend:latest
